# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ObjectEditor.ui'
#
# Created: Wed Dec 31 16:16:22 2014
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ObjectEditor(object):
    def setupUi(self, ObjectEditor):
        ObjectEditor.setObjectName(_fromUtf8("ObjectEditor"))
        ObjectEditor.resize(264, 897)
        self.gridLayout_3 = QtGui.QGridLayout(ObjectEditor)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label = QtGui.QLabel(ObjectEditor)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.name = QtGui.QLineEdit(ObjectEditor)
        self.name.setObjectName(_fromUtf8("name"))
        self.gridLayout_3.addWidget(self.name, 0, 1, 1, 2)
        self.label_2 = QtGui.QLabel(ObjectEditor)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.x = QtGui.QSpinBox(ObjectEditor)
        self.x.setMaximum(10000)
        self.x.setObjectName(_fromUtf8("x"))
        self.gridLayout_3.addWidget(self.x, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(ObjectEditor)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.y = QtGui.QSpinBox(ObjectEditor)
        self.y.setMaximum(10000)
        self.y.setObjectName(_fromUtf8("y"))
        self.gridLayout_3.addWidget(self.y, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(ObjectEditor)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 3, 0, 1, 1)
        self.comboBox = QtGui.QComboBox(ObjectEditor)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.comboBox, 3, 1, 1, 2)
        self.label_7 = QtGui.QLabel(ObjectEditor)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 4, 0, 1, 1)
        self.texture = QtGui.QLineEdit(ObjectEditor)
        self.texture.setObjectName(_fromUtf8("texture"))
        self.gridLayout_3.addWidget(self.texture, 4, 1, 1, 2)
        self.orbit = QtGui.QGroupBox(ObjectEditor)
        self.orbit.setObjectName(_fromUtf8("orbit"))
        self.gridLayout = QtGui.QGridLayout(self.orbit)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.a = QtGui.QSpinBox(self.orbit)
        self.a.setMaximum(1000)
        self.a.setObjectName(_fromUtf8("a"))
        self.gridLayout.addWidget(self.a, 2, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.orbit)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.orbit)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 2, 0, 1, 1)
        self.speed = QtGui.QDoubleSpinBox(self.orbit)
        self.speed.setDecimals(6)
        self.speed.setMinimum(-99.99)
        self.speed.setObjectName(_fromUtf8("speed"))
        self.gridLayout.addWidget(self.speed, 3, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.orbit)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 3, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.orbit)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 1)
        self.b = QtGui.QSpinBox(self.orbit)
        self.b.setMaximum(1000)
        self.b.setObjectName(_fromUtf8("b"))
        self.gridLayout.addWidget(self.b, 1, 1, 1, 1)
        self.center = QtGui.QLineEdit(self.orbit)
        self.center.setObjectName(_fromUtf8("center"))
        self.gridLayout.addWidget(self.center, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.orbit, 5, 0, 1, 3)
        self.waypointsBox = QtGui.QGroupBox(ObjectEditor)
        self.waypointsBox.setObjectName(_fromUtf8("waypointsBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.waypointsBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.attack = QtGui.QLineEdit(self.waypointsBox)
        self.attack.setObjectName(_fromUtf8("attack"))
        self.gridLayout_2.addWidget(self.attack, 1, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.waypointsBox)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 1, 0, 1, 1)
        self.defense = QtGui.QLineEdit(self.waypointsBox)
        self.defense.setObjectName(_fromUtf8("defense"))
        self.gridLayout_2.addWidget(self.defense, 2, 1, 1, 1)
        self.waypoints = QtGui.QLineEdit(self.waypointsBox)
        self.waypoints.setObjectName(_fromUtf8("waypoints"))
        self.gridLayout_2.addWidget(self.waypoints, 0, 0, 1, 2)
        self.label_14 = QtGui.QLabel(self.waypointsBox)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.waypointsBox, 6, 0, 1, 3)
        self.label_8 = QtGui.QLabel(ObjectEditor)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 7, 0, 1, 1)
        self.desc = QtGui.QTextEdit(ObjectEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.desc.sizePolicy().hasHeightForWidth())
        self.desc.setSizePolicy(sizePolicy)
        self.desc.setObjectName(_fromUtf8("desc"))
        self.gridLayout_3.addWidget(self.desc, 8, 0, 1, 3)
        self.label_5 = QtGui.QLabel(ObjectEditor)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 9, 0, 1, 1)
        self.prices = QtGui.QTableWidget(ObjectEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prices.sizePolicy().hasHeightForWidth())
        self.prices.setSizePolicy(sizePolicy)
        self.prices.setProperty("showDropIndicator", False)
        self.prices.setShowGrid(False)
        self.prices.setWordWrap(False)
        self.prices.setCornerButtonEnabled(False)
        self.prices.setObjectName(_fromUtf8("prices"))
        self.prices.setColumnCount(1)
        self.prices.setRowCount(9)
        item = QtGui.QTableWidgetItem()
        self.prices.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.prices.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.prices.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.prices.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.prices.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.prices.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.prices.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.prices.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.prices.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.prices.setHorizontalHeaderItem(0, item)
        self.prices.horizontalHeader().setVisible(True)
        self.prices.horizontalHeader().setHighlightSections(False)
        self.prices.verticalHeader().setVisible(True)
        self.prices.verticalHeader().setHighlightSections(False)
        self.gridLayout_3.addWidget(self.prices, 10, 0, 1, 3)
        self.label_6 = QtGui.QLabel(ObjectEditor)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 11, 0, 1, 1)
        self.items = QtGui.QListWidget(ObjectEditor)
        self.items.setObjectName(_fromUtf8("items"))
        self.gridLayout_3.addWidget(self.items, 12, 0, 1, 3)
        self.addItem = QtGui.QPushButton(ObjectEditor)
        self.addItem.setObjectName(_fromUtf8("addItem"))
        self.gridLayout_3.addWidget(self.addItem, 13, 0, 1, 1)
        self.removeItem = QtGui.QPushButton(ObjectEditor)
        self.removeItem.setObjectName(_fromUtf8("removeItem"))
        self.gridLayout_3.addWidget(self.removeItem, 13, 2, 1, 1)
        self.pushButton = QtGui.QPushButton(ObjectEditor)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_3.addWidget(self.pushButton, 15, 0, 1, 1)
        self.editDialogs = QtGui.QPushButton(ObjectEditor)
        self.editDialogs.setObjectName(_fromUtf8("editDialogs"))
        self.gridLayout_3.addWidget(self.editDialogs, 14, 0, 1, 3)

        self.retranslateUi(ObjectEditor)
        QtCore.QMetaObject.connectSlotsByName(ObjectEditor)

    def retranslateUi(self, ObjectEditor):
        ObjectEditor.setWindowTitle(_translate("ObjectEditor", "Form", None))
        self.label.setText(_translate("ObjectEditor", "Name:", None))
        self.label_2.setText(_translate("ObjectEditor", "X:", None))
        self.label_3.setText(_translate("ObjectEditor", "Y:", None))
        self.label_4.setText(_translate("ObjectEditor", "Type:", None))
        self.comboBox.setItemText(0, _translate("ObjectEditor", "Planet", None))
        self.comboBox.setItemText(1, _translate("ObjectEditor", "Star", None))
        self.comboBox.setItemText(2, _translate("ObjectEditor", "Ship", None))
        self.comboBox.setItemText(3, _translate("ObjectEditor", "Enemy ship", None))
        self.label_7.setText(_translate("ObjectEditor", "Texture:", None))
        self.orbit.setTitle(_translate("ObjectEditor", "Orbit", None))
        self.label_9.setText(_translate("ObjectEditor", "Center:", None))
        self.label_11.setText(_translate("ObjectEditor", "Elipse b:", None))
        self.label_12.setText(_translate("ObjectEditor", "Speed:", None))
        self.label_10.setText(_translate("ObjectEditor", "Elipse a:", None))
        self.waypointsBox.setTitle(_translate("ObjectEditor", "Waypoints", None))
        self.label_13.setText(_translate("ObjectEditor", "Attack:", None))
        self.label_14.setText(_translate("ObjectEditor", "Defense:", None))
        self.label_8.setText(_translate("ObjectEditor", "Desc:", None))
        self.label_5.setText(_translate("ObjectEditor", "Prices:", None))
        item = self.prices.verticalHeaderItem(0)
        item.setText(_translate("ObjectEditor", "Engine", None))
        item = self.prices.verticalHeaderItem(1)
        item.setText(_translate("ObjectEditor", "Fuel", None))
        item = self.prices.verticalHeaderItem(2)
        item.setText(_translate("ObjectEditor", "Food", None))
        item = self.prices.verticalHeaderItem(3)
        item.setText(_translate("ObjectEditor", "Ship imp.", None))
        item = self.prices.verticalHeaderItem(4)
        item.setText(_translate("ObjectEditor", "Extra food", None))
        item = self.prices.verticalHeaderItem(5)
        item.setText(_translate("ObjectEditor", "Machine", None))
        item = self.prices.verticalHeaderItem(6)
        item.setText(_translate("ObjectEditor", "Gun", None))
        item = self.prices.verticalHeaderItem(7)
        item.setText(_translate("ObjectEditor", "Ship weapon", None))
        item = self.prices.verticalHeaderItem(8)
        item.setText(_translate("ObjectEditor", "Ship shield", None))
        item = self.prices.horizontalHeaderItem(0)
        item.setText(_translate("ObjectEditor", "Price", None))
        self.label_6.setText(_translate("ObjectEditor", "Items:", None))
        self.addItem.setText(_translate("ObjectEditor", "Add", None))
        self.removeItem.setText(_translate("ObjectEditor", "Remove", None))
        self.pushButton.setText(_translate("ObjectEditor", "Save", None))
        self.editDialogs.setText(_translate("ObjectEditor", "Edit Dialogs", None))

